version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    container_name: django_mine_db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9500
    volumes:
      - .:/code
    ports:
      - "9500:9500"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    restart: always
    container_name: django_mine_web
